version: '3.9'
services:
  nginx:
    build: ./nginx_dockerfile
    #  context: nginx_dockerfile
    volumes:
      - ./nginx_bind/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx_appvhost/app.vhost:/etc/nginx/conf.d/app.vhost
      - ./nginx_logs/Nginx:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    networks:
      - phpmariadb
    depends_on:
      - fpm

  fpm:
    build: ./php_dockerfile
    #  context: php_dockerfile    
    image: phpdocker
    container_name: php
    #ports:
    # - 9000:9000
    volumes:
      - ./app/:/var/www/html/
    #command: php -S 0.0.0.0:9000 
    networks:
      - phpmariadb
    depends_on:
      - mysql

  mysql:
    image: mariadb:10.7
    container_name: mariadb 
    ports:
      - 3306:3306
    volumes:
      - ./app_data/:/var/lib/mysql
    networks:
      - phpmariadb
    environment:
      - MYSQL_ROOT_PASSWORD=T14dm00@@
      - MYSQL_PASSWORD=T14dm00
      - MYSQL_USER=alpha
      - MYSQL_DATABASE=alpha_db

networks:
  phpmariadb:
    driver: bridge
    
