version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - slack/notify:
      event: fail
      template: basic_fail_1  
      mentions: "@channel"
      #
      - slack/notify:
           event: pass
           template: success_tagged_deploy_1
      # - slack/notify:
      #     custom: |
      #       {
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "fields": [
      #               {
      #                 "type": "plain_text",
      #                 "text": "*This is a text notification*",
      #                 "emoji": true
      #               }
      #             ]
      #           }
      #         ]
      #       }
      #     event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets