version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:  
  build:
    docker:
      - image: 'cimg/base:stable'  
    steps:
      #      
        - slack/notify:
              event: fail
              mentions: '@channel'
              template: basic_fail_1              
        - slack/notify:
              event: pass
              mentions: '@channel'
              template: basic_success_1           

workflows:
  send-notification:
    jobs:
      - build:
          context: slack-secrets
          filters:
            tags:
              only:
                - /^hotfix.*/
          