version: 2.1
orbs:
  slack: circleci/slack@4.9.3

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_job_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

jobs:  
  build:
    parameters:
      env:
        description: "Ambiente selecionado para fazer a build"
        default: "dev"
        type: string
      run_migration:
        default: true
        type: boolean
    docker:
      - image: cimg/openjdk:8.0-node 
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .

  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - notify_slack_error  
      - notify_slack_job_pass
            

workflows:
  send-notification:
    jobs:
      - build:
          env: dev-platform    
    notify:
      requires: 
        - build
      context: slack-secrets

                    
          # filters:
          #   branches:
          #     only:
          #       - /master(?:-.+)?$/
          