version: 2.1
orbs:
  slack: circleci/slack@4.9.3

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_job_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1   

jobs:  
  build:
    docker:
      - image: cimg/openjdk:8.0-node 
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
      # - when:
      #     condition:
      #       equal: [ feature/2ft2h85, << pipeline.git.branch >> ]
      #     steps:
      - notify_slack_error
      - notify_slack_job_pass
            

workflows:
  send-notification:
    jobs:
      - build:
          context: slack-secrets          
          filters:
            branches:
              only:
                - /feature.*/
          