version: 2.1
orbs:
  slack: circleci/slack@4.9.3

commands:
  notify_slack_error:
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1

  notify_slack_job_pass:
    steps:
      - slack/notify:
          event: pass
          template: basic_success_1

  success_tagged_deploy_1: |
                        {
                        	"text": "CircleCI job succeeded!",
                        	"blocks": [
                        		{
                        			"type": "header",
                        			"text": {
                        				"type": "plain_text",
                        				"text": "Deployment Successful! :tada:",
                        				"emoji": true
                        			}
                        		},
                        		{
                        			"type": "section",
                        			"fields": [
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Project*: $CIRCLE_PROJECT_REPONAME"
                        				},
                        				{
                        					"type": "mrkdwn",
                        					"text": "*When*: $(date +'%m/%d/%Y %T')"
                        				},
                        				{
                        					"type": "mrkdwn",
                        					"text": "*Job*: $CIRCLE_JOB"
                        				}
                        			],
                        			"accessory": {
                        				"type": "image",
                        				"image_url": "https://assets.brandfolder.com/otz5mn-bw4j2w-6jzqo8/original/circle-logo-badge-black.png",
                        				"alt_text": "CircleCI logo"
                        			}
                        		},
                        		{
                        			"type": "actions",
                        			"elements": [
                        				{
                        					"type": "button",
                        					"text": {
                        						"type": "plain_text",
                        						"text": "View Job"
                        					},
                        					"url": "${CIRCLE_BUILD_URL}"
                        				}
                        			]
                        		}
                        	]
                        }
                name: Slack - Sending Notification
                when: always          

jobs:  
  build:
    docker:
      - image: cimg/openjdk:8.0-node 
    steps:
      - persist_to_workspace:
          root: .
          paths:
            - .
      - when:
          condition:
            equal: [ feature/2ft2h85, << pipeline.git.branch >> ]
          steps:
            - notify_slack_error
            - success_tagged_deploy_1
            

workflows:
  send-notification:
    jobs:
      - build:
          context: slack-secrets          
          filters:
            branches:
              only:
                - /^feature.*/
          