version: 2.1
orbs:
  slack: circleci/slack@4.9.3
jobs:
  notify:
    docker:
      - image: 'cimg/base:stable'
    steps:
      #      
        - slack/notify:    
              branch_pattern: master
              event: fail
              mentions: '@channel'
              template: basic_fail_1
              #
        - slack/notify:      
              branch_pattern: master 
              event: pass
              mentions: '@channel'
              template: success_tagged_deploy_1
      # - slack/notify:
      #     custom: |
      #       {
      #         "blocks": [
      #           {
      #             "type": "section",
      #             "fields": [
      #               {
      #                 "type": "plain_text",
      #                 "text": "*This is a text notification*",
      #                 "emoji": true
      #               }
      #             ]
      #           }
      #         ]
      #       }
          # event: always
workflows:
  send-notification:
    jobs:
      - notify:
          context: slack-secrets